### ISSUE TITLE
no support for alternate paths and virtualenv

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [pghilardi/atom-python-test#4]
basically all projects i do use py.test on (including py.test itself) use virtualenvs
i dont see a option/way to use it on that proejct

**Comment by pghilardi** [comment]
Hi Ronny!

If you have a virtualenv activated and open Atom, the plug-in will search and run the py.test available in the PATH of this environment.

Right now, I added the possibility to customize the py.test executable on plug-in settings (open atom settings and go to atom-python-test settings). This is available after version 0.1.8 (launched today).

Could you test if this solve your problem?

**Comment by RonnyPfannschmidt** [comment]
depends, is there a way to have those options per project/folder

if i open the first atom instance in project A and the second atom instance in project b, the result would be a unhappy me otherwise

**Comment by pghilardi** [comment]
Currently Atom doesn't supports well virtualenv. Exists a plug-in (https://github.com/jhutchins/virtualenv) to change environments dynamically, but it isn't working  :(

AFAK, you should open one Atom instance per environment to Atom respect your virtualenv and work as your expectations.

Anyway, I will test with different envs here and I will return to this topic with more info.

**Comment by pghilardi** [comment]
Ronny,

I have tested using different virtualenvs with Atom and Atom Python Test. For me, which works is:
- Activate your desired virtualenv on terminal
- Execute atom from this virtualenv. Atom will use py.test contained in this virtualenv.

If you want to use other version of py.test in other virtualenv, you must close Atom, activate the other virtualenv and then re-open atom to use the proper py.test.

Anyway, now Atom Python Test allows to specify a custom py.test path.

**Comment by RonnyPfannschmidt** [comment]
i usually have between 2 and 4 atom instances opened in different projects so off hand (also untested) i dont see how that helps

**Comment by pghilardi** [comment]
Hum. Probably I'm not understanding your workflow and your requirements. 

What is your use case? I'm supposing that you open one atom instance and inside that you have more than one project opened. So your idea is that each project should use a different virtualenv?

And you open another atom instance with another bunch of projects and do you want to configure different virtualenvs for each project on this other atom instance.

Is this the use case?

Because if you open each project in a different Atom instance which is on a different virtualenv, Atom will get the right py.test from the virtualenv.
